Metrics/LineLength:
  Exclude:
    - spec/*


# Offense count: 5
Metrics/AbcSize:
  Max: 64

# Offense count: 4
Metrics/CyclomaticComplexity:
  Max: 21

# Offense count: 5
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 40

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 177

# Offense count: 2
Metrics/PerceivedComplexity:
  Max: 20
